kind: Service
apiVersion: v1
metadata:
  name: spark-expose-dashboard
  namespace: spark-cluster
  labels:
    component: spark-master
#    kubernetes.io/cluster-service: "true"
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      nodePort: 30200
      targetPort: 8080
  selector:
    component: spark-master

